### ISSUE TITLE
WPF controls support

### ISSUE THREAD

**Issue by arkadam02** [leviwilson/mohawk#11]
Can I use this gem to test comples WPF applications. I am testing windows WPF complex application, where there are lot custom controls are used, will I be able use mohawk gem for automation of such application.

**Comment by leviwilson** [comment]
If you are able to inspect / modify with UISpy or other similar tools, it
will work with this.

**Comment by arkadam02** [comment]
I set up my environment for Mohawk gem , but now I am running into an issue. I have password text box with Classname: PasswordBox , it does not have automation id or name. How to identify this element. are there any other properties I could use to identify such elements.

Thanks 
Aparna

**Comment by leviwilson** [comment]
You should be able to use `class: 'PasswordBox'` as the locator.

**Comment by arkadam02** [comment]
Thanks for getting back to me. I tries with class:passwordBox a and still could not find password box element. I am putting here the password filed from xaml file, it is not of type Textbox 

 <c:SePasswordBox x:Name="passwordTextbox" Style="{StaticResource DarkSePasswordBox}" Grid.Column="1" Grid.Row="2" Margin="0,4,0,4"
                         b:SelectAllOnTabFocus.Active="true" />

Please guide what should i use to identify this field.

Thanks
Aparna

**Comment by leviwilson** [comment]
I wouldn't be able to tell you without the UISpy dump of the screen.

I'm going to close this issue unless there is something specific that is an
issue with mohawk.
