### ISSUE TITLE
Mohawk with uia 0.6

### ISSUE THREAD

**Issue by rs-mphasis** [leviwilson/mohawk#14]
Hi leviwilson,
                     Could you please facilitate an updated version of mohawk - with uia 0.6 as the dependency?
_Reason:_ 
mohawk 0.4.3, is currently dependent on uia 0.5 - which doesn't seem to work (for me) on Win 10 using ruby 2.4.x/2.5.x (32 bit).

Potential root cause: uia 0.5 being locked to ffi 1.9.0. 

Error Observed: 
cannot load such file -- ffi_c (LoadError)
C:/Ruby25/lib/ruby/gems/2.5.0/gems/ffi-1.9.0-x86-mingw32/lib/ffi.rb:14:in `require'
C:/Ruby25/lib/ruby/gems/2.5.0/gems/ffi-1.9.0-x86-mingw32/lib/ffi.rb:14:in `rescue in <top (required)>'
C:/Ruby25/lib/ruby/gems/2.5.0/gems/ffi-1.9.0-x86-mingw32/lib/ffi.rb:3:in `<top (required)>'

P.S. uia 0.6 works fine.

Kindly assist. Thank You!

**Comment by leviwilson** [comment]
You can just `bundle update uia` or specify that version in your project, correct?

**Comment by leviwilson** [comment]
Setting the [`mohawk.gemspec`](https://github.com/leviwilson/mohawk/blob/master/mohawk.gemspec#L21) file to `gem.add_dependency 'uia', '~> 0.5` just says that it has to at _least_ be `uia` version `0.5`.

There's nothing stopping you from using `uia` version `0.6` in your project so I might be missing where you problem might be.

If you can checkin a project that you're working on that is *not* working I can take a look.

**Comment by rs-mphasis** [comment]
Hi leviwilson,
                     Seems like the root cause of LoadError is 'require_all' gem v 2.0.0. I validated using v 1.5.0 of 'require_all' and ran into the '[BUG] Segmentation fault' issue (resolution to which is described in wiki of uia gem). 

To conclude, I had to downgrade to ruby 2.4.5 to work with ffi 1.9.18 (to resolve Segmentation fault). Below updates to Gemfile work fine for me now.

gem 'mohawk'
gem 'uia', '0.6'
gem 'ffi', '1.9.18'
gem 'require_all' , '1.5.0'

Thank You for your time and support!
